name: Run Benchmarks

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]  # Run on main branch pushes

permissions:
  contents: write

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install package and test dependencies
        run: |
          python -m pip install pytest numpy
          python -m pip install -e .

      - name: Run tests
        run: python -m pytest tests/

      - name: Install benchmark dependencies
        run: |
          python -m pip install matplotlib zstandard

      - name: Run benchmark
        run: |
          python devel/benchmark.py

      - name: Configure Git
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Create fresh results branch
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          git checkout --orphan benchmark-results
          git rm -rf .
          mkdir -p benchmark-results

      - name: Move benchmark files
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          mv benchmark_output/benchmark.json benchmark-results/
          mv benchmark_output/benchmark.png benchmark-results/

      - name: Commit benchmark results
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add benchmark-results/
          git commit -m "Update benchmark results from $(date +'%Y-%m-%d %H:%M:%S') [skip ci]"
          git push -f https://${GITHUB_TOKEN}@github.com/${{ github.repository }} benchmark-results
